### ISSUE TITLE
Incorrect platform tag in binary wheels

### ISSUE THREAD

**Issue by scop** [asottile/setuptools-download#5]
Not sure where this issue is, setuptools-download, shellcheck-py config, or somewhere else, but filing here:

Building binary wheels out of setuptools-download powered packages seems to yield platform tags that are not good for PyPI. This happens at least on Linux.

Reproduces with current shellcheck-py main branch. Tested with `python3 -m build`, `python3 setup.py bdist_wheel`, and `pip wheel --no-deps .`, the Linux wheel ends up with platform tag `linux_x86_64`. Trying to upload such a wheel yields an error from PyPI:

```
Binary wheel '...-py2.py3-none-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'.
```

Not sure if other platforms' tags besides Linux would be good, FWIW for a project I'm working on (pretty much just copy-pasted from shellcheck-py) they ended up as `macosx_10_9_universal2` and `win_amd64`. At least "universal" in the macOS one sounds suspicious, as it contains only an arm64 binary.

**Comment by scop** [comment]
In retrospect, maybe this is a shellcheck-py issue, but already filed here, so I suppose it can be discussed here.

**Comment by asottile** [comment]
as with any Linux wheel you must run it through auditwheel after building

**Comment by asottile** [comment]
(usually via a manylinux docker image)
